### ISSUE TITLE
Hello server

### ISSUE THREAD

**Issue by aharalambopoulos** [DylanVanAssche/Qt-Server-Sent-Events-Demo#1]
Hi Dylan, Could you please extend your nice demo with a server sending "Hello World" every 10 sec. for example?

**Comment by DylanVanAssche** [comment]
The demo server is added :)
Enjoy :tada:

**Comment by aharalambopoulos** [comment]
Thank you for the server, but I meant a demo server using QT5 and not nodejs. I am having issues with an application using qt5 and cutelyst. 

You can have a look here 

https://github.com/cutelyst/cutelyst/issues/257
